---
# handlers file for ansible-network.config_store
#
- name: "trigger git_sync"
  include_tasks: "includes/git_flow.yaml"
  listen: git_sync
  run_once: yes

- name: "remove local repo"
  file:
    path: "{{ config_store_working_dir }}"
    state: absent
  run_once: yes
